### PR TITLE
Uses task-boot to deploy to pypi

### PR DESCRIPTION
**Pull request by ShriramK**
See issue #30

### CODE REVIEW

**Review by marco-c — COMMENTED** [review]
Thanks, looks good so far!
Could you remove the infra/pypi.py file though, as it's not needed anymore now?

**Review by marco-c — APPROVED** [review]

**Comment by marco-c** [comment]
Looks good, but there is a linting failure to fix.
You can use pre-commit for that.

**Comment by marco-c** [comment]
Why did you close this and open a new one?

**Comment by ShriramK** [comment]
Because of 
https://github.com/mozilla/microannotate/pull/57/commits/de7501f03211ef1ed348e19103ad9ddcd977937b
I accessed the merge or update branch button on this pull request by mistake.
When I tried to push the commit with lint failure fix, I saw the branches diverged.
So I thought for linear history deleting this remote branch and creating a rebased new branch made sense. That closed the pull request.

**Comment by marco-c** [comment]
No there's no need, you can just do `git push origin pypi --force` and de7501f will be overwritten.

**Comment by marco-c** [comment]
Indeed, there is no difference between this PR and the other you have opened. So I'll close that and reopen this.

**Comment by marco-c** [comment]
Mmmh, it seems like I can't reopen this one... So I'll reopen the other and merge the other.
Anyway, don't do this in general, it pollutes the history of PRs (e.g. the review history of this PR is now lost, as the other PR will be merged directly with no review).

**Comment by ShriramK** [comment]
I recall now that using the --force option is the proper thing to do. I will keep this in mind and not  pollute the history of PRs again.

**Pull request closed without merging**
